import "unknwn.idl";

[
  uuid(F5D56A47-4C01-4C07-A033-3C8B87787F71),
  helpstring("Library with access to retranslator"),
  //control
]
library RetranslatorLib 
{
  //importlib("stdole32.tlb");
  importlib("stdole2.tlb");
  
  // Main class interface
  [
    object,
    uuid(097344BD-7C6B-4F8C-9787-78C85E9EAC8B),
    version(1.0),
    helpstring("Interface for Retranslator class"),
    oleautomation,
    dual
  ]
  interface IRetranslator : IDispatch 
  {
    [id(20)] HRESULT getWeight([out, retval] long *res);
    [id(22)] HRESULT getWeightFixed([out, retval] long *res);
    [id(24)] HRESULT getMinimalWeight([out, retval] long *res);
    [id(25)] HRESULT getCorr([out, retval] long *res);

    [id(26)] HRESULT setMinimalWeight([in] long val);
    [id(27)] HRESULT setCorr([in] long corr);
    [id(28)] HRESULT setNull();

    [id(30)] HRESULT getStatus([out, retval] long *err_status);
    [id(31)] HRESULT getAuth([out, retval] long *f_auth);
    [id(32)] HRESULT getStab([out, retval] long *f_stability);

    [id(33)] HRESULT clearAuth();
  }

  [
    uuid(6425EC19-B96A-4648-B24A-52997A34911E),
    helpstring("Retranslator class"),
    //control
  ]
  coclass RetranslatorAX
  {
    [default] interface IRetranslator;
    interface IDispatch;
  }

  // Interface for RetranslatorUtils class
  [
      //{A5DAA4D9-6271-4DE3-9AA4-3232B839BFFD}
      object,
      uuid(A5DAA4D9-6271-4DE3-9AA4-3232B839BFFD),
      version(1.0),
      helpstring("Interface for RetranslatorUtils class"),
      oleautomation,
      dual
  ]
  interface IRetranslatorUtils : IDispatch
  {
      [id(10)] HRESULT run([in, string, ref] char* cmd);
      [id(11)] HRESULT runW([in, ref] VARIANT* cmd);
      [id(20)] HRESULT setTimeout([in] unsigned long ms_timeout);
  }

  [
      //{280F8E09-7C79-403C-A944-436C5A66EFB6}
      uuid(280F8E09-7C79-403C-A944-436C5A66EFB6),
      helpstring("RetranslatorUtils class"),
      //control
  ]
  coclass RetranslatorUtilsAX
  {
      [default] interface IRetranslatorUtils;
      interface IDispatch;
  }


  //// Interface for RetranslatorComPort class
  //[
  //    //{2898B2A8-3096-4A0A-9581-CD09F4D1070E}
  //    object,
  //    uuid(2898B2A8-3096-4A0A-9581-CD09F4D1070E),
  //    version(1.0),
  //    helpstring("Interface for RetranslatorComPort class"),
  //    oleautomation,
  //    dual
  //]
  //interface IRetranslatorComPort : IDispatch
  //{
  //  [id(10)] HRESULT openPort([in] unsigned long port_n, [in] unsigned long baudrate, [in] unsigned long bytesize, [out, retval] long *status);
  //  [id(11)] HRESULT closePort();

  //  [id(15)] HRESULT setSoftwareSuffix([in] byte suffix);
  //  [id(16)] HRESULT setReadTimeout([in] long ms, [out, retval] long *status);
  //  
  //  [id(20)] HRESULT write([in, string, ref] const byte* info);
  //  [id(21)] HRESULT read(unsigned long read_size, [out, retval, string]BSTR* read_info);

  //  [id(30)] HRESULT getLastError([out, retval] long *status);
  //}

  //[
  //    //{520CD17F-F06D-4E80-BE7B-A44FC07B9870}
  //    uuid(520CD17F-F06D-4E80-BE7B-A44FC07B9870),
  //    helpstring("RetranslatorComPort class"),
  //    //control
  //]
  //coclass RetranslatorComPort
  //{
  //    [default] interface IRetranslatorComPort;
  //    interface IDispatch;
  //}
}
